/**
 * Friendly aliases over the ambient types generated by
 * `php artisan typescript:transform` (see generated.d.ts, which declares the
 * `App.Domain.*` namespaces). Import app-wide types from here:
 *
 *   import type { TenantData } from '@/types';
 *
 * The DTO is the single source of truth — never hand-edit generated.d.ts.
 */

export type TenantData = App.Domain.Tenancy.Data.TenantData;
export type CreateTenantData = App.Domain.Tenancy.Data.CreateTenantData;
export type PlanOptionData = App.Domain.Tenancy.Data.PlanOptionData;
export type TenantStatus = App.Domain.Tenancy.Enums.TenantStatus;
export type TenantPlan = App.Domain.Tenancy.Enums.TenantPlan;
export type TenantFeature = App.Domain.Tenancy.Enums.TenantFeature;
