/**
 * Friendly aliases over the ambient types generated by
 * `php artisan typescript:transform` (see generated.d.ts, which declares the
 * `App.Domain.*` namespaces). Import app-wide types from here:
 *
 *   import type { TenantData } from '@/types';
 *
 * The DTO is the single source of truth — never hand-edit generated.d.ts.
 */

export type TenantData = App.Domain.Tenancy.Data.TenantData;
export type CreateTenantData = App.Domain.Tenancy.Data.CreateTenantData;
export type PlanOptionData = App.Domain.Tenancy.Data.PlanOptionData;
export type TenantStatus = App.Domain.Tenancy.Enums.TenantStatus;
export type TenantPlan = App.Domain.Tenancy.Enums.TenantPlan;
export type TenantFeature = App.Domain.Tenancy.Enums.TenantFeature;

/**
 * Membership (Slice 002). Aliases over the generated `App.Domain.Membership.*`
 * namespaces (regenerated by `php artisan typescript:transform`). The backed
 * enum is the single source of truth — never hand-edit generated.d.ts.
 */
export type MemberRole = App.Domain.Membership.Enums.MemberRole;
export type MemberData = App.Domain.Membership.Data.MemberData;
export type LoginData = App.Domain.Membership.Data.LoginData;
export type InviteMemberData = App.Domain.Membership.Data.InviteMemberData;
export type UpdateMemberRoleData = App.Domain.Membership.Data.UpdateMemberRoleData;

/**
 * Platform admin console (Slice 003). The console pages model their props with
 * local row shapes (snake_case, matching the central controllers); the only
 * generated types they consume are the `TenantStatus` / `TenantPlan` enums
 * aliased above. The full `App.Domain.Platform.Data.*` DTO aliases are
 * intentionally omitted here until the backend runs
 * `php artisan typescript:transform` and they land in generated.d.ts — adding
 * them before then would reference a namespace that does not yet exist.
 */
